name        : mpg123
version     : 1.20.1
release     : 2
source      :
    - http://downloads.sourceforge.net/mpg123/mpg123-1.20.1.tar.bz2 : da2941c1905b5776d5468209896502a8d5257966dfadc07f1e4ea105cc515900
homepage    : http://www.mpg123.de/
component   : multimedia.codecs
license     : LGPL-2.1
summary     : Console based mp3 decoder
description : |
    Console based mp3 decoder
patterns    :
    - bin : [/usr/bin, /usr/share/man]
emul32      : yes
builddeps   :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(flac)
    - pkgconfig32(json-c)
    - pkgconfig32(ogg)
    - pkgconfig32(sndfile)
    - pkgconfig32(vorbis)
    - glibc-32bit-devel
    - libgcc-32bit
setup      : |
    %configure --with-module-suffix=.so
build      : |
    %make
install    : |
    %make_install
replaces   :
    - libmpg123
    - devel : libmpg123-devel
