name       : mpg123
version    : 1.26.3
release    : 20
source     :
    - https://sourceforge.net/projects/mpg123/files/mpg123/1.26.3/mpg123-1.26.3.tar.bz2 : 30c998785a898f2846deefc4d17d6e4683a5a550b7eacf6ea506e30a7a736c6e
homepage   : https://www.mpg123.de/
component  : multimedia.codecs
license    : LGPL-2.1-only
summary    : Console based mp3 decoder
description: |
    mpg123 is a fast and Free real time MPEG Audio Layer 1, 2 and 3 decoding library and console player. It uses floating point or integer math, along with several special optimizations (3DNow, SSE, ARM, ...) to make it most efficient.
emul32     : yes
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man
replaces   :
    - libmpg123
    - devel : libmpg123-devel
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(flac)
    - pkgconfig32(json-c)
    - pkgconfig32(ogg)
    - pkgconfig32(sndfile)
    - pkgconfig32(vorbis)
setup      : |
    %configure --enable-int-quality
build      : |
    %make
install    : |
    %make_install
