name       : mpg123
version    : 1.24.0
release    : 5
source     :
    - http://downloads.sourceforge.net/mpg123/mpg123-1.24.0.tar.bz2 : 55fb169a7711938f5df0497d1ffe28419fbef50011dc01d00b216379e6a2256c
homepage   : http://www.mpg123.de/
component  : multimedia.codecs
license    : LGPL-2.1
summary    : Console based mp3 decoder
description: |
    Console based mp3 decoder
patterns   :
    - bin : [/usr/bin, /usr/share/man]
replaces   :
    - libmpg123
    - devel : libmpg123-devel

emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(flac)
    - pkgconfig32(json-c)
    - pkgconfig32(ogg)
    - pkgconfig32(sndfile)
    - pkgconfig32(vorbis)
setup      : |
    %configure --with-module-suffix=.so
build      : |
    %make
install    : |
    %make_install
