name       : mpg123
version    : 1.25.0
release    : 6
source     :
    - http://downloads.sourceforge.net/mpg123/mpg123-1.25.0.tar.bz2 : 552e3e1db045e00f474252917007795ac295863fc8b13891859b3382d2f24e48
homepage   : http://www.mpg123.de/
component  : multimedia.codecs
license    : LGPL-2.1
summary    : Console based mp3 decoder
description: |
    Console based mp3 decoder
patterns   :
    - bin : [/usr/bin, /usr/share/man]
replaces   :
    - libmpg123
    - devel : libmpg123-devel

emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(flac)
    - pkgconfig32(json-c)
    - pkgconfig32(ogg)
    - pkgconfig32(sndfile)
    - pkgconfig32(vorbis)
setup      : |
    %configure --enable-int-quality \
               --with-module-suffix=.so
build      : |
    %make
install    : |
    %make_install
