name       : mpg123
version    : 1.31.3
release    : 24
source     :
    - https://sourceforge.net/projects/mpg123/files/mpg123/1.31.3/mpg123-1.31.3.tar.bz2 : 1ca77d3a69a5ff845b7a0536f783fee554e1041139a6b978f6afe14f5814ad1a
homepage   : https://www.mpg123.de/
component  :
    - multimedia.codecs
    - bin : multimedia.codecs
license    : LGPL-2.1-only
summary    : Console based mp3 decoder
description: |
    mpg123 is a fast and Free real time MPEG Audio Layer 1, 2 and 3 decoding library and console player. It uses floating point or integer math, along with several special optimizations (3DNow, SSE, ARM, ...) to make it most efficient.
emul32     : yes
patterns   :
    - bin :
        - /usr/bin
        - /usr/share/man
replaces   :
    - libmpg123
    - devel : libmpg123-devel
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(json-c)
    - pkgconfig32(sndfile)
setup      : |
    %configure --enable-int-quality
build      : |
    %make
install    : |
    %make_install
