name       : mpg123
version    : 1.25.2
release    : 9
source     :
    - https://pilotfiber.dl.sourceforge.net/project/mpg123/mpg123/1.25.2/mpg123-1.25.2.tar.bz2 : 5314b0fb8ad291bfc79ff4c5c321b971916819a65233ec065434358fcf8aee38
homepage   : https://www.mpg123.de/
component  : multimedia.codecs
license    : LGPL-2.1
summary    : Console based mp3 decoder
description: |
    mpg123 is a fast and Free real time MPEG Audio Layer 1, 2 and 3
    decoding library and console player. It uses floating point or integer math,
    along with several special optimizations (3DNow, SSE, ARM, ...) to make it
    most efficient.
patterns   :
    - bin : [/usr/bin, /usr/share/man]
replaces   :
    - libmpg123
    - devel : libmpg123-devel

emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(flac)
    - pkgconfig32(json-c)
    - pkgconfig32(ogg)
    - pkgconfig32(sndfile)
    - pkgconfig32(vorbis)
setup      : |
    %configure --enable-int-quality
build      : |
    %make
install    : |
    %make_install
