name       : mpg123
version    : 1.25.7
release    : 12
source     :
    - https://pilotfiber.dl.sourceforge.net/project/mpg123/mpg123/1.25.7/mpg123-1.25.7.tar.bz2 : 31b15ebcf26111b874732e07c8e60de5053ee555eea15fb70c657a4f9f0344f3
homepage   : https://www.mpg123.de/
component  : multimedia.codecs
license    : LGPL-2.1
summary    : Console based mp3 decoder
description: |
    mpg123 is a fast and Free real time MPEG Audio Layer 1, 2 and 3
    decoding library and console player. It uses floating point or integer math,
    along with several special optimizations (3DNow, SSE, ARM, ...) to make it
    most efficient.
patterns   :
    - bin : [/usr/bin, /usr/share/man]
replaces   :
    - libmpg123
    - devel : libmpg123-devel

emul32     : yes
builddeps  :
    - pkgconfig32(alsa)
    - pkgconfig32(libpulse)
    - pkgconfig32(flac)
    - pkgconfig32(json-c)
    - pkgconfig32(ogg)
    - pkgconfig32(sndfile)
    - pkgconfig32(vorbis)
setup      : |
    %configure --enable-int-quality
build      : |
    %make
install    : |
    %make_install
